Fix malarkey.directive.ts change private to public
Fix this error:
ERROR in [default] myApp/src/app/components/malarkey/malarkey.directive.ts:25:18
Property 'malarkey' does not exist on type 'MalarkeyController'.